export { AppService } from './app.service';
export { DepartmentsService } from './departments.service';
export { DisciplinesService } from './disciplines.service';
export { FacultiesService } from './faculties.service';
export { GroupsService } from './groups.service';
export { NewsService } from './news.service';
export { SchedulesService } from './schedules.service';
export { StudentsService } from './students.service';
export { TeachersService } from './teachers.service';
